version: '2'
services:  
  node:
    build: ./web
    ports:
      - "8080:8080"
    links:
      - mongo:db
    volumes:
      - ./web/app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - HOST_IP=138.197.134.40
    command: npm start


  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
  
  nginx:
    build: ./nginx
    image: sqwak/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - node:api
    ports:
      - "80:80"
      - "443:443"