version: '2'
services:
  node:
    build: ./web
    volumes:
      - ./web/app:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build: ./nginx
