version: '2'
services:


  node:
    build: ./web
    ports:
      - "8080:8080"
    links:
      - mongo:db
    volumes:
      - ./web/app:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "8082:3000"
    volumes:
      - ./frontend/app:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
