version: '2'
services:
  node:
    build: ./web
    ports:
      - "8080:8080"
    links:
      - mongo:db
    volumes:
      - ./web/app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - HOST_IP=138.197.134.40
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "8082:3000"
    volumes:
      - ./frontend/app:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    links:
      - node:api 
    environment:
      - REACT_APP_API_URL=localhost:8080

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
  
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - node:api
    ports:
      - "80:80"
      - "443:443"
